eZeljeznice.Web/Areas/ModulAdministracija/Controllers/TipZaposlenikaController.cs
using eZeljeznice.Data.Model;
using eZeljeznice.Web.Areas.ModulAdministracija.Models;
using eZeljeznice.Web.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eZeljeznice.Web.Areas.ModulAdministracija.Controllers
{
    [Autorizacija(true)]
    public class TipZaposlenikaController : Controller
    {
        // GET: ModulAdministracija/TipZaposlenika
        MojContext mc = new MojContext();
        // GET: ModulAdministracija/Uloga
        public ActionResult Index()
        {
            TipZaposlenikaPrikaziVM model = new TipZaposlenikaPrikaziVM();
            model.TipoviZaposlenika = mc.TipoviZaposlenika.Select(x => new TipZaposlenikaPrikaziVM.TipZaposlenikaInfo
            {
                Id = x.Id,
                Naziv = x.Naziv,
                Opis = x.Opis
            }).ToList();

            return View("Prikazi", model);
        }

        public ActionResult Uredi(int tipZaposlenikaId)
        {
            TipZaposlenika tz = mc.TipoviZaposlenika.Find(tipZaposlenikaId);
            TipZaposlenikaUrediVM model = new TipZaposlenikaUrediVM();
            model.Id = tz.Id;
            model.Naziv = tz.Naziv;
            model.Opis = tz.Opis;


            return View("Uredi", model);
        }
        public ActionResult Obrisi(int tipZaposlenikaId)
        {
            TipZaposlenika tz = mc.TipoviZaposlenika.Find(tipZaposlenikaId);
      
            mc.TipoviZaposlenika.Remove(tz);

            try { mc.SaveChanges(); } catch { }

            return RedirectToAction("Index");
        }
        public ActionResult Dodaj()
        {
            TipZaposlenikaUrediVM model = new TipZaposlenikaUrediVM();


            return View("Uredi", model);
        }
        public ActionResult Snimi(TipZaposlenikaUrediVM tz)
        {

            if (!ModelState.IsValid)
            {
               
                return View("Uredi", tz);


            }

            TipZaposlenika tipDB;
            if (tz.Id == 0)
            {
                tipDB = new TipZaposlenika();
                mc.TipoviZaposlenika.Add(tipDB);

            }
            else
            {
                tipDB = mc.TipoviZaposlenika.Where(x => x.Id == tz.Id).FirstOrDefault();

            }

            tipDB.Naziv = tz.Naziv;
            tipDB.Opis = tz.Opis;

            mc.SaveChanges();

       

            return RedirectToAction("Index");
        }
    }
}

eZeljeznice.Web/Areas/ModulAdministracija/Views/TipZaposlenika/Prikazi.cshtml
@model eZeljeznice.Web.Areas.ModulAdministracija.Models.TipZaposlenikaPrikaziVM

@using eZeljeznice.Web.Areas.ModulAdministracija.Models



<div class="panel">


    <div id="content-wrapper">



        <div class="table-light">
            <div class="table-header">
                <div class="table-caption">
                   Tipovi zaposlenika
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>

                        <th>Naziv</th>
                        <th>Opis</th>
                        <th>Akcija</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (TipZaposlenikaPrikaziVM.TipZaposlenikaInfo x in Model.TipoviZaposlenika)
                    {

                        <tr>
                            <td>@x.Naziv</td>
                            <td>@x.Opis</td>
                            <td>
                                <a class="btn btn-danger btn-sm" style="color:black" href="/ModulAdministracija/TipZaposlenika/Obrisi?tipZaposlenikaId=@x.Id">Obriši</a>
                                @Ajax.ActionLink("Uredi", "Uredi", new { tipZaposlenikaId = x.Id }, new AjaxOptions { UpdateTargetId = "ajax-tip-zaposlenika" }, new { @class = "btn btn-primary btn-sm" })

                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            @Ajax.ActionLink("Dodaj novi", "Dodaj", null, new AjaxOptions { UpdateTargetId = "ajax-tip-zaposlenika" }, new { @class = "btn btn-primary btn-sm" })


        </div>

        <div class="panel panel-success col-md-5">

            <div id="ajax-tip-zaposlenika">



            </div>

        </div>



    </div>


</div>

eZeljeznice.Web/Areas/ModulAdministracija/Views/TipZaposlenika/Uredi.cshtml
@model eZeljeznice.Web.Areas.ModulAdministracija.Models.TipZaposlenikaUrediVM
  
@{
    Layout = null;
}


   


    <div>

        @Html.ActionLink("Nazad", "Index")
    </div>

    @if (Model.Id <= 0)
    {
        <h4>Dodaj tip zaposlenika</h4>
    }
    else
    {
        <h4> Uredi tip zaposlenika</h4>
    }


    @using (Html.BeginForm("Snimi", "TipZaposlenika", FormMethod.Post, new { @name = "form", @onsubmit = "return validateNaziv()" }))
    {


        <div class="form-horizontal">



            @Html.HiddenFor(model => model.Id)


            <div class="form-group">

                <div class="col-md-8">
                     
                    <label for="Naziv">Naziv:</label>
                   <span id="validation" class="text-danger" style="display:none">Obavezno polje</span>
                    @Html.TextBoxFor(model => model.Naziv, new { @class = "form-control", name="Naziv", @id="Naziv" })

                </div>
            </div>
            <div class="form-group">

                <div class="col-md-8">

                    <label for="Opis">Opis:</label>
                    @Html.TextAreaFor(model => model.Opis, new { @class = "form-control", @rows = "4" })

                </div>
            </div>


            <div class="form-group">
                <div class="col-md-10">

                    <input type="submit" value="Sačuvaj" class="btn btn-success btn-sm" />

                </div>
            </div>

        </div>


    }