eZeljeznice.Web/Areas/ModulAdministracija/Controllers/TipKarteController.cs
using eZeljeznice.Data.Model;
using eZeljeznice.Web.Areas.ModulAdministracija.Models;
using eZeljeznice.Web.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eZeljeznice.Web.Areas.ModulAdministracija.Controllers
{
    [Autorizacija(true)]
    public class TipKarteController : Controller
    {
        // GET: ModulAdministracija/TipKarte
        MojContext mc = new MojContext();

        public ActionResult Index()
        {
            TipKartePrikaziVM model = new TipKartePrikaziVM();
            model.TipoviKarte = mc.TipoviKarte.Select(x => new TipKartePrikaziVM.TipKarteInfo
            {
                Id = x.Id,
                Naziv = x.Naziv,
                Popust=x.Popust
            }).ToList();

            return View("Prikazi", model);
        }

        public ActionResult Uredi(int tipKarteId)
        {
            TipKarte tk = mc.TipoviKarte.Find(tipKarteId);
            TipKarteUrediVM model = new TipKarteUrediVM();
            model.Id = tk.Id;
            model.Naziv = tk.Naziv;
            model.Popust = tk.Popust;


            return View("Uredi", model);
        }
        public ActionResult Obrisi(int tipKarteId)
        {
            TipKarte tk = mc.TipoviKarte.Find(tipKarteId);

            mc.TipoviKarte.Remove(tk);

            try { mc.SaveChanges(); } catch { }

            return RedirectToAction("Index");
        }
        public ActionResult Dodaj()
        {
            TipKarteUrediVM model = new TipKarteUrediVM();


            return View("Uredi", model);
        }
        public ActionResult Snimi(TipKarteUrediVM tk)
        {

            if (!ModelState.IsValid)
            {

                return View("Uredi", tk);


            }

            TipKarte tipDB;
            if (tk.Id == 0)
            {
                tipDB = new TipKarte();
                mc.TipoviKarte.Add(tipDB);

            }
            else
            {
                tipDB = mc.TipoviKarte.Where(x => x.Id == tk.Id).FirstOrDefault();

            }

            tipDB.Naziv = tk.Naziv;
            tipDB.Popust = tk.Popust;

            mc.SaveChanges();



            return RedirectToAction("Index");
        }
    }
}

eZeljeznice.Web/Areas/ModulAdministracija/Views/TipKarte/Prikazi.cshtml
@model eZeljeznice.Web.Areas.ModulAdministracija.Models.TipKartePrikaziVM

@using eZeljeznice.Web.Areas.ModulAdministracija.Models



<div class="panel">


    <div id="content-wrapper">



        <div class="table-light">
            <div class="table-header">
                <div class="table-caption">
                 Tipovi karte
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>

                        <th>Naziv</th>
                        <th>Popust</th>
                        <th>Akcija</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (TipKartePrikaziVM.TipKarteInfo x in Model.TipoviKarte)
                    {

                        <tr>
                            <td>@x.Naziv</td>
                            <td>@x.Popust %</td>
                            <td>
                                <a class="btn btn-danger btn-sm" style="color:black" href="/ModulAdministracija/TipKarte/Obrisi?tipKarteId=@x.Id">Obriši</a>
                                @Ajax.ActionLink("Uredi", "Uredi", new { tipKarteId = x.Id }, new AjaxOptions { UpdateTargetId = "ajax-tip-karte" }, new { @class = "btn btn-primary btn-sm" })

                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            @Ajax.ActionLink("Dodaj novi", "Dodaj", null, new AjaxOptions { UpdateTargetId = "ajax-tip-karte" }, new { @class = "btn btn-primary btn-sm" })


        </div>

        <div class="panel panel-success col-md-5">

            <div id="ajax-tip-karte">



            </div>

        </div>



    </div>


</div>

eZeljeznice.Web/Areas/ModulAdministracija/Views/TipKarte/Uredi.cshtml
@model eZeljeznice.Web.Areas.ModulAdministracija.Models.TipKarteUrediVM
  
@{
    Layout = null;
}


   


    <div>

        @Html.ActionLink("Nazad", "Index")
    </div>

    @if (Model.Id <= 0)
    {
        <h4>Dodaj tip karte</h4>
    }
    else
    {
        <h4> Uredi tip karte</h4>
    }


    @using (Html.BeginForm("Snimi", "TipKarte", FormMethod.Post, new { @name = "form", @onsubmit = "return validateNaziv()" }))
    {


        <div class="form-horizontal">



            @Html.HiddenFor(model => model.Id)


            <div class="form-group">

                <div class="col-md-8">
                     
                    <label for="Naziv">Naziv:</label>
                   <span id="validation" class="text-danger" style="display:none">Obavezno polje</span>
                    @Html.TextBoxFor(model => model.Naziv, new { @class = "form-control", name="Naziv", @id="Naziv" })

                </div>
            </div>
            <div class="form-group">

                <div class="col-md-3">

                    <label for="Popust">Popust:</label>
                    @Html.TextBoxFor(model => model.Popust, new { @class = "form-control", @type = "number", @max="100", @min="0" })

                </div>
            </div>


            <div class="form-group">
                <div class="col-md-10">

                    <input type="submit" value="Sačuvaj" class="btn btn-success btn-sm" />

                </div>
            </div>

        </div>


    }