eZeljeznice.Web/Areas/ModulAdministracija/Controllers/GradController.cs
using eZeljeznice.Data.Model;
using eZeljeznice.Web.Areas.ModulAdministracija.Models;
using eZeljeznice.Web.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eZeljeznice.Web.Areas.ModulAdministracija.Controllers
{
    [Autorizacija(true)]
    public class GradController : Controller
    {
        MojContext mc = new MojContext();
        // GET: ModulAdministracija/Drzava
        public ActionResult Index(int kantonId)
        {
            GradPrikaziVM model = new GradPrikaziVM();
            model.Kanton = mc.Kantoni.Find(kantonId).Naziv;
            model.KantonId = kantonId;

            model.Gradovi = mc.Gradovi.Where(x=>x.KantonId==kantonId).ToList().
                Select(x => new GradPrikaziVM.GradInfo
            {
                Id = x.Id,
                Naziv = x.Naziv,
                PostanskiBroj = x.PostanskiBroj
               

            }).ToList();
            return View("Prikazi", model);
        }


        public ActionResult Uredi(int gradId)
        {

            GradUrediVM model = new GradUrediVM();
            Grad g = mc.Gradovi.Where(x => x.Id == gradId).FirstOrDefault();
            model.Id = g.Id;
            model.Naziv = g.Naziv;
            model.PostanskiBroj = g.PostanskiBroj;
            model.KantonId = g.KantonId;
          

            return View("Uredi", model);
        }
        public ActionResult Dodaj(int kantonId)
        {

            GradUrediVM model = new GradUrediVM();
            model.KantonId = kantonId;
          

            return View("Uredi", model);
        }
        public ActionResult Obrisi(int gradId)
        {

            Grad g = mc.Gradovi.Find(gradId);
            mc.Gradovi.Remove(g);
            mc.SaveChanges();


            return RedirectToAction("Index", new { kantonId = g.KantonId });
        }
        public ActionResult Snimi(GradUrediVM grad)
        {
            if (!ModelState.IsValid)
            {
               
                return View("Uredi", grad);
              
            }

            Grad gradDB;
            if (grad.Id == 0)
            {

                gradDB = new Grad();
                mc.Gradovi.Add(gradDB);

            }

            else
            {

                gradDB = mc.Gradovi.Where(x => x.Id == grad.Id).FirstOrDefault();
            }

            gradDB.Naziv = grad.Naziv;
            gradDB.PostanskiBroj =grad.PostanskiBroj;
            gradDB.KantonId = grad.KantonId;



            mc.SaveChanges();


            return RedirectToAction("Index", new { kantonId = grad.KantonId });
        }


    }
}

eZeljeznice.Web/Areas/ModulAdministracija/Views/Grad/Prikazi.cshtml
@model eZeljeznice.Web.Areas.ModulAdministracija.Models.GradPrikaziVM

@using eZeljeznice.Web.Areas.ModulAdministracija.Models


@{ Layout = null;}



    <div>



        <div class="table-light">
            <div class="table-header">
                <div class="table-caption">
                     @Model.Kanton - Gradovi
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>

                        <th>Naziv</th>
                        <th>Oznaka</th>
                   
                        <th>Akcija</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (GradPrikaziVM.GradInfo x in Model.Gradovi)
                    {

                        <tr>
                            <td>@x.Naziv</td>
                            <td>@x.PostanskiBroj</td>
                           
                            <td>
                                @Ajax.ActionLink("Obrisi", "Obrisi", new { gradId = x.Id }, new AjaxOptions { UpdateTargetId = "ajax-kanton" }, new { @class = "btn btn-danger btn-sm" })


                                @Ajax.ActionLink("Uredi", "Uredi", new { gradId = x.Id }, new AjaxOptions { UpdateTargetId = "ajax-grad" }, new { @class = "btn btn-primary btn-sm" })
                              
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            @Ajax.ActionLink("Dodaj novi", "Dodaj", new {kantonId=Model.KantonId }, new AjaxOptions { UpdateTargetId = "ajax-grad" }, new { @class = "btn btn-primary btn-sm" })


        </div>

        <div>

            <div id="ajax-grad">



            </div>

        </div>



    </div>

eZeljeznice.Web/Areas/ModulAdministracija/Views/Grad/Uredi.cshtml
@model eZeljeznice.Web.Areas.ModulAdministracija.Models.GradUrediVM

@{
    Layout = null;
}



<div class="panel col-md-6">

    <div>

        @Ajax.ActionLink("Nazad", "Index",new {kantonId=Model.KantonId }, new AjaxOptions { UpdateTargetId = "ajax-kanton" })
    </div>

    @if (Model.Id <= 0)
    {
        <h4>Dodaj grad</h4>
    }
    else
    {
        <h4> Uredi grad</h4>
    }


    @using (Ajax.BeginForm("Snimi", "Grad",null, new AjaxOptions { UpdateTargetId = "ajax-kanton",OnBegin= "return validateNaziv()" }, new { @name = "form" }))
    {


        <div class="form-horizontal">



            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.KantonId)


            <div class="form-group">

                <div class="col-md-8">

                    <label for="Naziv">Naziv:</label>
                    <span id="validation" class="text-danger" style="display:none">Obavezno polje</span>
                    @Html.TextBoxFor(model => model.Naziv, new { @class = "form-control", name = "Naziv", @id = "Naziv" })

                </div>
            </div>


            <div class="form-group">

                <div class="col-md-3">

                    <label for="PostaniskiBroj">Poštanski broj:</label>
                    @Html.TextBoxFor(model => model.PostanskiBroj, new { @class = "form-control" })

                </div>
            </div>


            <div class="form-group">
                <div class="col-md-10">

                    <input type="submit" value="Sačuvaj" class="btn btn-success btn-sm" />

                </div>
            </div>

        </div>


    }



</div>