eZeljeznice.Web/Areas/ModulAdministracija/Controllers/DrzavaController.cs
using eZeljeznice.Data.Model;
using eZeljeznice.Web.Areas.ModulAdministracija.Models;
using eZeljeznice.Web.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eZeljeznice.Web.Areas.ModulAdministracija.Controllers
{
    [Autorizacija(true)]
    public class DrzavaController : Controller
    {
        MojContext mc = new MojContext();
        // GET: ModulAdministracija/Drzava
        public ActionResult Index()
        {
            DrzavaPrikaziVM model = new DrzavaPrikaziVM();

            model.Drzave = mc.Drzave.Select(x => new DrzavaPrikaziVM.DrzavaInfo
            {
                Id = x.Id,
                Naziv=x.Naziv,
                Oznaka=x.Oznaka

            }).ToList();
            return View("Prikazi", model);
        }


        public ActionResult Uredi(int drzavaId)
        {

            DrzavaUrediVM model = new DrzavaUrediVM();
            Drzava d = mc.Drzave.Where(x => x.Id == drzavaId).FirstOrDefault();
            model.Id = d.Id;
            model.Naziv = d.Naziv;
            model.Oznaka = d.Oznaka;

            return View("Uredi", model);
        }
        public ActionResult Dodaj()
        {

            DrzavaUrediVM model = new DrzavaUrediVM();
      

            return View("Uredi", model);
        }
        public ActionResult Obrisi(int drzavaId)
        {

            Drzava d = mc.Drzave.Find(drzavaId);
            mc.Drzave.Remove(d);
            try { mc.SaveChanges(); } catch { }
      


            return RedirectToAction("Index");
        }
        public ActionResult Snimi(DrzavaUrediVM drzava)
        {
            if (!ModelState.IsValid)
            {

                return View("Uredi", drzava);
            }

            Drzava drzavaDB;
            if (drzava.Id == 0)
            {

                drzavaDB = new Drzava();
                mc.Drzave.Add(drzavaDB);

            }

            else
            {

                drzavaDB = mc.Drzave.Where(x => x.Id == drzava.Id).FirstOrDefault();
            }

            drzavaDB.Naziv = drzava.Naziv;
            drzavaDB.Oznaka = drzava.Oznaka;


          
            mc.SaveChanges();


            return RedirectToAction("Index");
        }


    }
}

eZeljeznice.Web/Areas/ModulAdministracija/Views/Drzava/Prikazi.cshtml
@model eZeljeznice.Web.Areas.ModulAdministracija.Models.DrzavaPrikaziVM

@using eZeljeznice.Web.Areas.ModulAdministracija.Models



<div class="panel">


    <div id="content-wrapper">



        <div class="table-light">
            <div class="table-header">
                <div class="table-caption">
                    Države
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>

                        <th>Naziv</th>
                        <th>Oznaka</th>
                        <th>Akcija</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (DrzavaPrikaziVM.DrzavaInfo x in Model.Drzave)
                    {

                        <tr>
                            <td>@x.Naziv</td>
                            <td>@x.Oznaka</td>
                            <td>
                                @Html.ActionLink("Obrisi", "Obrisi", new { drzavaId = x.Id }, new { @class = "btn btn-danger btn-sm" })
                                @Ajax.ActionLink("Uredi", "Uredi","Drzava", new { drzavaId = x.Id }, new AjaxOptions { UpdateTargetId = "ajax-drzava" }, new { @class = "btn btn-primary btn-sm" })
                                @Ajax.ActionLink("Kantoni", "Index","Kanton", new { drzavaId = x.Id }, new AjaxOptions { UpdateTargetId = "ajax-drzava" }, new { @class = "btn btn-info btn-sm" })


                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            @Ajax.ActionLink("Dodaj novu", "Dodaj", null, new AjaxOptions { UpdateTargetId = "ajax-drzava" }, new { @class = "btn btn-primary btn-sm" })


        </div>

      

        <div id="ajax-drzava">


        </div>

    </div>

</div>

eZeljeznice.Web/Areas/ModulAdministracija/Views/Drzava/Uredi.cshtml
@model eZeljeznice.Web.Areas.ModulAdministracija.Models.DrzavaUrediVM

@{
    Layout = null;
}




<div class="panel col-md-6">
    <div>

        @Html.ActionLink("Nazad", "Index")
    </div>

    @if (Model.Id <= 0)
    {
        <h4>Dodaj državu</h4>
    }
    else
    {
        <h4> Uredi državu</h4>
    }


    @using (Html.BeginForm("Snimi", "Drzava", FormMethod.Post, new { @name = "form", @onsubmit = "return validateNaziv()" }))
    {


        <div class="form-horizontal">



            @Html.HiddenFor(model => model.Id)


            <div class="form-group">

                <div class="col-md-8">

                    <label for="Naziv">Naziv:</label>
                    <span id="validation" class="text-danger" style="display:none">Obavezno polje</span>
                    @Html.TextBoxFor(model => model.Naziv, new { @class = "form-control", name = "Naziv", @id = "Naziv" })

                </div>
            </div>
            <div class="form-group">

                <div class="col-md-2">

                    <label for="Oznaka">Oznaka:</label>
                    @Html.TextBoxFor(model => model.Oznaka, new { @class = "form-control" })

                </div>
            </div>


            <div class="form-group">
                <div class="col-md-10">

                    <input type="submit" value="Sačuvaj" class="btn btn-success btn-sm" />

                </div>
            </div>

        </div>


    }



       </div>